### ISSUE TITLE
Authentification failed

### ISSUE THREAD

**Issue by paul-henriz** [PhiGi87/dashing-whmcs-tickets#1]
Hi,

I've setup your wonderful module for dashing, but i have an error.
WHMCS returns "Authentification Failed 403".
I've whitelisted the public of dashing, and my credentials are correct, and have the permission to API access.
Thank you in advance for your help,

Regards

**Comment by PhiGi87** [comment]
Hi, sorry I was not active for a long time. Have you created the Accesskey in WHMCS? You often only need it when you use the smartphone app.

http://docs.whmcs.com/AWHMCS_Android_App#Setup_Instructions

**Comment by PhiGi87** [comment]
I have commit an update for you. I could not test it yet. I test it afterwards, if you are not faster ;)
